version: '3.7'
services:

  softether:
    image: anti1346/softethervpn
    build: .
    container_name: softether
    restart: unless-stopped
    environment:
      - VPNROOTDIR=/usr/local/vpnserver
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      #- './config/vpn_server.config:${VPNROOTDIR}/vpn_server.config'
      #- './config/chain_certs:${VPNROOTDIR}/chain_certs'
      - './config/backup.vpn_server.config:${VPNROOTDIR}/backup.vpn_server.config'
      - './logs/packet_log:${VPNROOTDIR}/packet_log'
      - './logs/security_log:${VPNROOTDIR}/security_log'
      - './logs/server_log:${VPNROOTDIR}/server_log'
    privileged: true
    #network_mode: host
    ports:
    #  - '443:443'
    #  - '992:992'
    #  - '1194:1194'
      - '5555:5555'
