version: '3.7'
services:

  softether:
    image: anti1346/softether
    build: .
    container_name: softether_vpn
    restart: unless-stopped
    environment:
      APP_ROOT: /usr/local
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      #- './config/vpn_server.config:${APP_ROOT}/vpnserver/vpn_server.config'
      #- './config/chain_certs:${APP_ROOT}/vpnserver/chain_certs'
      - './logs/packet_log:${APP_ROOT}/vpnserver/packet_log'
      - './logs/security_log:${APP_ROOT}/vpnserver/security_log'
      - './logs/server_log:${APP_ROOT}/vpnserver/server_log'
      - './config/backup.vpn_server.config:${APP_ROOT}/vpnserver/backup.vpn_server.config'
    privileged: true
    #network_mode: host
    ports:
      - '443:443'
      - '992:992'
      - '1194:1194'
      - '5555:5555'
